### ISSUE TITLE
Error when ran

### ISSUE THREAD

**Issue by DarkDaedelus** [hoelsner/python-script-examples#1]
When executing the example, I get the following error:

python '/home/user/Desktop/interface-description-cleaner.py' 
----------------------------------------
start the interface description cleaner 
----------------------------------------
request CDP information for switch: 192.168.127.130
Traceback (most recent call last):
  File "/home/user/Desktop/interface-description-cleaner.py", line 157, in <module>
    remote_host = neighbor['device_id'].split("(")[1]
TypeError: string indices must be integers

Unfortunately I don' t have enough experience to fix it myself.

**Comment by hoelsner** [comment]
Hi DarkDaedelus, 

I think you get an unexpected response from the NXAPI. Can you please add a `print(neighbor)` before the `remote_host = neighbor['device_id'].split("(")[1]` and post the output to the issue? Which NX-OS version do you use? 

Greetings, Henry

**Comment by DarkDaedelus** [comment]
Henry,

I am testing with vNX-OS, with 2 hosts, 192.168.127.130 and 132.
Username/password on  both are admin/admin
Changed the https port to 444

I am running into different problems now:
Running with Python2:
python2 '/home/user/Desktop/interface-description-cleaner.py' 
Traceback (most recent call last):
  File "/home/user/Desktop/interface-description-cleaner.py", line 32, in <module>
    requests.packages.urllib3.disable_warnings()
AttributeError: 'module' object has no attribute 'disable_warnings'


Running with Python3:
python3 '/home/user/Desktop/interface-description-cleaner.py' 
----------------------------------------
start the interface description cleaner 
----------------------------------------
request CDP information for switch: 192.168.127.130
/usr/lib/python3/dist-packages/urllib3/connectionpool.py:794: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
Traceback (most recent call last):
  File "/home/user/Desktop/interface-description-cleaner.py", line 157, in <module>
    remote_host = neighbor['device_id'].split("(")[0]
TypeError: string indices must be integers

After adding " print(neighbor)" , the output shows "v4mgmtaddr " :
user@ubuntu:~$ python3 '/home/user/Desktop/interface-description-cleaner.py' 
----------------------------------------
start the interface description cleaner 
----------------------------------------
request CDP information for switch: 192.168.127.130
/usr/lib/python3/dist-packages/urllib3/connectionpool.py:794: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
v4mgmtaddr
Traceback (most recent call last):
  File "/home/user/Desktop/interface-description-cleaner.py", line 158, in <module>
    remote_host = neighbor['device_id'].split("(")[0]
TypeError: string indices must be integers

**Comment by hoelsner** [comment]
Hi DarkDaedelus, 

first, I don't test the scrips with python 2, therefore you need to use python3. 

I think that the result from the NX-API is different from what I expect in the script, but I have currently no NX-OS box to test it. To see the full response from the switch, add a `print(result)` in line 149 (after the `nxapi_cli_show` function call) and post it here or send it via email to me.

Greetings, Henry

**Comment by jchristopher327** [comment]
Hey @hoelsner ,

I'm running into the same `TypeError: string indices must be integers` error. Below is the `print(result)` output. I did manage to get this working on a 3K running 7.0.3.I2.2e but receive the error on a 9K running 7.0.3.I5.2. The sandbox json-rpc output is structured a bit different from these two devices so that may be the cause of the issue.
```
python /etc/python_scripts/interface-description.py 
----------------------------------------
start the interface description cleaner 
----------------------------------------
request CDP information for switch: x.x.x.x
{u'jsonrpc': u'2.0', u'result': {u'body': {u'TABLE_cdp_neighbor_detail_info': {u'ROW_cdp_neighbor_detail_info': {u'sysname': u'evpn-spine-2', u'intf_id': u'Ethernet1/50', u'num_mgmtaddr': 1, u'v4mgmtaddr': u'x.x.x.x', u'syslocation': u'snmplocation', u'mtu': 9216, u'platform_id': u'N9K-C9236C', u'duplexmode': u'full', u'version': u'Cisco Nexus Operating System (NX-OS) Software, Version 7.0(3)I5(2)', u'numaddr': 1, u'ttl': 145, u'ifindex': 436232704, u'capability': [u'router', u'switch', u'Supports-STP-Dispute'], u'version_no': u'v2', u'port_id': u'Ethernet1/1', u'v4addr': u'x.x.x.x', u'device_id': u'evpn-spine-2.internal.xxxx.com(FDO202911WH)'}}}}, u'id': 1}
Traceback (most recent call last):
  File "/etc/python_scripts/interface-description.py", line 150, in <module>
    remote_host = neighbor['device_id'].split("(")[0]
TypeError: string indices must be integers
```

**Comment by jchristopher327** [comment]
Added `print(neighbor)` and the output for this is `sysname`. I expect that it should be `device_id`, correct?
```
request CDP information for switch: x.x.x.x
{u'jsonrpc': u'2.0', u'result': {u'body': {u'TABLE_cdp_neighbor_detail_info': {u'ROW_cdp_neighbor_detail_info': {u'sysname': u'evpn-spine-2', u'intf_id': u'Ethernet1/50', u'num_mgmtaddr': 1, u'v4mgmtaddr': u'x.x.x.x', u'syslocation': u'snmplocation', u'mtu': 9216, u'platform_id': u'N9K-C9236C', u'duplexmode': u'full', u'version': u'Cisco Nexus Operating System (NX-OS) Software, Version 7.0(3)I5(2)', u'numaddr': 1, u'ttl': 155, u'ifindex': 436232704, u'capability': [u'router', u'switch', u'Supports-STP-Dispute'], u'version_no': u'v2', u'port_id': u'Ethernet1/1', u'v4addr': u'x.x.x.x', u'device_id': u'evpn-spine-2.internal.xxxxx.com(FDXXXXX)'}}}}, u'id': 1}
sysname
Traceback (most recent call last):
  File "/etc/python_scripts/interface-description.py", line 151, in <module>
    remote_host = neighbor['device_id'].split("(")[0]
TypeError: string indices must be integers
```

**Comment by jchristopher327** [comment]
OK so I tried with another 9K running the same code but different model (93180YC-EX vs. C9236C) and it works as expected. The sandbox output is different between the two devices and is shown below (just showing the difference after the cdp_neighbor_detail_info). Going to open a case to see what can be done.

**93180YC-EX, device where error occurs**
```{
  "jsonrpc": "2.0",
  "result": {
    "body": {
      "TABLE_cdp_neighbor_detail_info": {
        "ROW_cdp_neighbor_detail_info": {
          "ifindex": 436232704,
          "device_id": "evpn-spine-2.internal.xxxx.com(FDOXXXX)",
          "sysname": "evpn-spine-2",
```

**C9236C, no error**
```{
  "jsonrpc": "2.0",
  "result": {
    "body": {
      "TABLE_cdp_neighbor_detail_info": {
        "ROW_cdp_neighbor_detail_info": [
          {
            "ifindex": 436207616,
            "device_id": "evpn-leaf-1.internal.xxxxx.com(FDOXXXXX)",
            "sysname": "evpn-leaf-1",```

**Comment by hoelsner** [comment]
Hi @jchristopher327, 

okay, I think I know what's wrong with the script. The expected type is a python list that contains the CDP neighbor details. It should work if you add the following code before the ` for neighbor in neighbor_statements:` (line 155):

```python
if type(neighbor_statements) is not list:
    # convert to a list if only a single entry in a dictionary is received from the device
    neighbor_statements = [neighbor_statements]
```

If this solution works for you, I'll update the script from the repository.

**Comment by jchristopher327** [comment]
@hoelsner, that fixes the issue. Thanks!

Also, small typo in line 127 `{ "from": "TenGigabirEthernet", "to": "Te"},`.
